#!/bin/bash

ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/vim" "$HOME/.vim"
ln -sf "$PWD/gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"


